/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package airswift;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 60111
 */
public class PaymentP extends javax.swing.JPanel {
    private Booking book;
    private AvailableSeat availableS;
    private Customer cust;  
    /**
     * Creates new form PaymentP
     */
    public PaymentP(Booking booking) {
        initComponents();
        //cust = new Customer();

        book = booking;
        //availableS = new AvailableSeat();
  
        TotPayment.setText(String.valueOf(booking.calculatePayment()));

    }
    
    boolean isFound = false;
    void readFile(){
        try{
            FileReader fr = new FileReader("Transaction.txt");
            
       
        } catch(FileNotFoundException ex){
            try{
            FileWriter writer = new FileWriter("Transaction.txt",true);
            } catch(IOException ex1){
                Logger.getLogger(PaymentP.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }
    
    public boolean isValidPhoneNumberFormat(String phoneNumber) {
        // Match the format +1 123-456-7890 or +12 123-456-7890 or +123 123-456-7890
        // or 1-123-456-7890 or 12-123-456-7890 or 123-123-456-7890 or 1234567890
        String regex = "\\+?\\d{0,3}[-\\s]?\\d{1,3}[-\\s]?\\d{3,}";
        return phoneNumber.matches(regex);
    }

    private String arrayToString(Object[] array) {
        if (array == null || array.length == 0) {
        return "";
    }

        StringBuilder result = new StringBuilder();
        result.append(array[0]);

        for (int i = 1; i < array.length; i++) {
            result.append(",");
            result.append(array[i]);
        }

        return result.toString();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        CardholderNameField = new javax.swing.JTextField();
        EmailAddressField = new javax.swing.JTextField();
        ConfirmPaymentButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JToggleButton();
        CardNumberField = new javax.swing.JFormattedTextField();
        SecurityCodeField = new javax.swing.JFormattedTextField();
        PhoneNumberField = new javax.swing.JTextField();
        CardType = new javax.swing.JComboBox<>();
        TotPayment = new javax.swing.JLabel();
        eDMonth = new com.toedter.calendar.JMonthChooser();
        eDYear = new com.toedter.calendar.JYearChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 550));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYMENT");
        jLabel1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("SELECT CREDIT CARD METHOD");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("CONTACT INFORMATION");

        CardholderNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true), "Cardholder's Name")));
        CardholderNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardholderNameFieldActionPerformed(evt);
            }
        });

        EmailAddressField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true), "Email Address"));
        EmailAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddressFieldActionPerformed(evt);
            }
        });

        ConfirmPaymentButton.setBackground(new java.awt.Color(153, 0, 0));
        ConfirmPaymentButton.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPaymentButton.setText("Confirm Payment");
        ConfirmPaymentButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, new java.awt.Color(102, 0, 0), java.awt.Color.white));
        ConfirmPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPaymentButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(204, 204, 204));
        CancelButton.setText("Cancel");
        CancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        CardNumberField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true), "Card Number"));
        try {
            CardNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumberFieldActionPerformed(evt);
            }
        });

        SecurityCodeField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true), "Security Code"));
        try {
            SecurityCodeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        SecurityCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecurityCodeFieldActionPerformed(evt);
            }
        });

        PhoneNumberField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true), "Phone Number"));
        PhoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberFieldActionPerformed(evt);
            }
        });

        CardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MasterCard", "Visa", " " }));
        CardType.setToolTipText("Card's Type");
        CardType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        CardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardTypeActionPerformed(evt);
            }
        });

        TotPayment.setMaximumSize(new java.awt.Dimension(90, 20));
        TotPayment.setMinimumSize(new java.awt.Dimension(90, 20));

        eDMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        eDYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel5.setText("Expiry Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("TOTAL PRICE:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(eDMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eDYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(CardNumberField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PhoneNumberField)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(EmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CardholderNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TotPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(28, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfirmPaymentButton)
                .addGap(38, 38, 38)
                .addComponent(CancelButton)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eDMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eDYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(CardholderNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(SecurityCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConfirmPaymentButton)
                            .addComponent(CancelButton))
                        .addGap(20, 20, 20))))
        );

        CardType.getAccessibleContext().setAccessibleName("");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airswift/Lyft _ Plane2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardTypeActionPerformed

    }//GEN-LAST:event_CardTypeActionPerformed

    private void PhoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberFieldActionPerformed
    
    
    }//GEN-LAST:event_PhoneNumberFieldActionPerformed

    private void SecurityCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecurityCodeFieldActionPerformed
        
    }//GEN-LAST:event_SecurityCodeFieldActionPerformed

    private void CardNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumberFieldActionPerformed
        
    }//GEN-LAST:event_CardNumberFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        new FlightMenu(cust).setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ConfirmPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPaymentButtonActionPerformed
        String custEmailAdress0 = book.getEmail();

        String flightID1 = book.getFlightID();
        String departShort2 = book.getDepartShort();
        String departLong3 = book.getDepartLong().toUpperCase();
        String returnShort4 = book.getReturnShort();
        String returnLong5= book.getReturnLong().toUpperCase();
        String passString6 = ""+book.getPassenger();
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("dd MMM yyyy");
        String departDate7 = dateFormat1.format(book.getDepartDate());
        String returnDate8 = "";
            if (book.getReturnDate() != null) {
                SimpleDateFormat dateFormat2 = new SimpleDateFormat("EEEE, dd MMMM yyyy", Locale.ENGLISH);
                returnDate8 = dateFormat2.format(book.getReturnDate()).toUpperCase();
            }
        String[] timeDepart = book.getTimeDepart();
        String[] timeReturn = book.getTimeReturn();

        String timeDepart9 = (timeDepart != null && timeDepart.length > 0) ? timeDepart[0] : "";
        String timeDepart22 = (timeDepart != null && timeDepart.length > 1) ? timeDepart[1] : "";
        String timeReturn10 = (timeReturn != null && timeReturn.length > 0) ? timeReturn[0] : "";
        String timeReturn23 = (timeReturn != null && timeReturn.length > 1) ? timeReturn[1] : "";

        String seatNames11 = (availableS != null && availableS.getSeatName() != null) ? String.join(", ", availableS.getSeatName()): "";
 
        String chName12 = CardholderNameField.getText();
        String eAddress13 = EmailAddressField.getText();
        String pNumber14 = PhoneNumberField.getText();
        String cNumber15 = CardNumberField.getText();
        String sCode16 = SecurityCodeField.getText();
        int Month17 = eDMonth.getMonth(); 
        int Year18 = eDYear.getYear();
        String cType19 = (String) CardType.getSelectedItem();
        
        String flightName20 = book.getFlightName();
        String cabin21 = book.getCabin();
        
        if (PhoneNumberField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill in the phone number");
            return;
        }
        // Check if the phone number matches the desired format
        if (!isValidPhoneNumberFormat(PhoneNumberField.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid phone number format");
        return;
        }
        
        if (SecurityCodeField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill in the security code");
        return;
        }
        
        if (CardNumberField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Fill in Credit Card Number");
            return;
        }
        
        if (CardholderNameField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Fill in the Card Holder Name");
            return;
        }
        
        if(!EmailAddressField.getText().contains("@") && !EmailAddressField.getText().contains(".com")){
            JOptionPane.showMessageDialog(this, "Email is not valid"); 
            return;
        }
        
        try {
            FileWriter wr = new FileWriter("Transaction.txt", true);
            // Save payment information as an array
            String[] paymentInfo = {
                custEmailAdress0,
                flightID1,
                departShort2,
                departLong3,
                returnShort4,
                returnLong5,
                passString6,
                departDate7,
                returnDate8 != null ? seatNames11 : "" ,
                timeDepart9, 
                timeReturn10 != null ? seatNames11 : "" ,
                seatNames11 != null ? seatNames11 : "" ,// If null, set as empty string
                chName12,
                eAddress13,
                pNumber14,
                cNumber15,
                sCode16,
                String.valueOf(Month17),
                String.valueOf(Year18),
                cType19,
                flightName20,
                cabin21,
                timeDepart22,
                timeReturn23 != null ? seatNames11 : "" 
            };

            // Convert the array to a CSV string and write to the file
             String paymentInfoCSV = String.join(",", paymentInfo);
        wr.write(paymentInfoCSV);
        wr.write(System.getProperty("line.separator"));

        wr.close();
        JOptionPane.showMessageDialog(null, "Success");
        setVisible(false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error");
    }
    new Receipt(cust).setVisible(true);
       
    }//GEN-LAST:event_ConfirmPaymentButtonActionPerformed

    private void EmailAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddressFieldActionPerformed
        
    }//GEN-LAST:event_EmailAddressFieldActionPerformed

    private void CardholderNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardholderNameFieldActionPerformed
        
    }//GEN-LAST:event_CardholderNameFieldActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CancelButton;
    private javax.swing.JFormattedTextField CardNumberField;
    private javax.swing.JComboBox<String> CardType;
    private javax.swing.JTextField CardholderNameField;
    private javax.swing.JButton ConfirmPaymentButton;
    private javax.swing.JTextField EmailAddressField;
    private javax.swing.JTextField PhoneNumberField;
    private javax.swing.JFormattedTextField SecurityCodeField;
    private javax.swing.JLabel TotPayment;
    private com.toedter.calendar.JMonthChooser eDMonth;
    private com.toedter.calendar.JYearChooser eDYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    void setBookingInformation(Booking book) {
        this.book = book;
    }
}
